name: Daily PR Analytics Update

on:
  schedule:
    # Run at 7:00 AM UTC (8:00 AM Berlin time during standard time, 9:00 AM during daylight saving)
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  update-analytics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dotenv
    
    - name: Fetch PR data
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        python src/fetch_pr_data.py
    
    - name: Commit data updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if there are changes to commit
        if [[ -n $(git status --porcelain) ]]; then
          git add data/
          git commit -m "Automated update: PR analytics data [skip ci]"
          git push origin main
          echo "Data updates committed successfully"
        else
          echo "No changes to commit"
        fi
    
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        path: gh-pages
    
    - name: Update dashboard files
      run: |
        # Copy updated data to gh-pages
        cp data/pr_metrics_all_prs.csv gh-pages/data/
        cp data/last_update.json gh-pages/data/
        
        # Copy dashboard files if they exist in main
        if [ -f deployment/index.html ]; then
          cp deployment/index.html gh-pages/
        fi
        
        # Create data directory if it doesn't exist
        mkdir -p gh-pages/data
    
    - name: Deploy to GitHub Pages
      working-directory: gh-pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Check if there are changes to commit
        if [[ -n $(git status --porcelain) ]]; then
          git add .
          git commit -m "Automated deployment: Update dashboard [skip ci]"
          git push origin gh-pages
          echo "Dashboard deployed successfully"
        else
          echo "No changes to deploy"
        fi
    
    - name: Verify deployment
      run: |
        echo "Deployment completed at $(date)"
        echo "Dashboard should be available at: https://aviv-fathallahelmasri.github.io/pr-analytics-dashboard/"
        echo "Note: GitHub Pages may take a few minutes to reflect the changes"
