name: PR Analytics Auto-Update Production

on:
  schedule:
    # Run at 7:00 AM UTC (8:00 AM Berlin time)
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-analytics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch PR data
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        GITHUB_REPO: axel-springer-kugawana/aviv_data_collection_contracts
      run: |
        echo "Fetching PR data..."
        python src/fetch_pr_data.py

    - name: Copy data to deployment folder
      run: |
        # Ensure deployment data directory exists
        mkdir -p deployment/data
        
        # Copy all data files to deployment folder
        cp -r data/* deployment/data/
        
        echo "✅ Data copied to deployment folder"
        
        # List files to verify
        echo "Files in deployment/data:"
        ls -la deployment/data/

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated update: PR analytics data ${{ github.run_number }}"
        branch: main
        file_pattern: data/* deployment/data/*
        commit_user_name: github-actions[bot]
        commit_user_email: github-actions[bot]@users.noreply.github.com

  deploy-pages:
    needs: update-analytics
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main  # Get the latest changes

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './deployment'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
